= Metode <Design>
Først gjennomføres en eksplorativ dataanalyse for å identifisere nødvendig datarensing og preprosessering før trening. Deretter deles dataene opp i et 80/20 trenings-/testsett. Som baseline bygges en "kitchen sink"-modell der alle tilgjengelige variabler brukes uten preprosessering, for å kunne sammenligne og vurdere ytelsen til den endelige modellen.
To typer maskinlæringsalgoritmer vil bli brukt: MLP og CNN. MLP fordi denne fungerer godt på strukturerte/tabulære data og kan lære komplekse, ikke-lineære sammenhenger mellom input-funksjoner. CNN fordi denne kan finne lokale mønstre og romlige avhengigheter i data (for eksempel i bilder eller sekvenser), noe som gir bedre gjenkjenning av mønstre.

Purpose: Explain how you approached the problem and why you made each choice.

== Forberedelse av data
=== MLP
Dataene ble normalisert ved hjelp av RobustScaler, som benytter median og interkvartilspredning i stedet for gjennomsnitt og standardavvik. Dette gjør normaliseringen mer robust overfor energitopper i RF-signaler, som kan gi kraftige utliggere dersom StandardScaler benyttes. Råsignalene ble prosessert med den samme glidende vinduesfunksjonen som CNN-modellen, og de 300 vinduene per opptak ble deretter komprimert til én flat feature-vektor ved hjelp av tre statistiske mål per frekvensbånd: gjennomsnitt, standardavvik og maksimum. Dette gir til sammen 192 egenskaper per opptak (32 bånd × 2 kanaler × 3 statistikker). Gjennomsnittsverdien representerer den typiske frekvensprofilen, standardavviket fanger temporal variasjon, og maksimum bevarer toppenergi uavhengig av tidspunkt. Klassebalansering ble ivaretatt gjennom stratifisert splitting (stratify=y) kombinert med frekvensbasert prøvevekting (sample_weight) under trening.

=== CNN
Råsignalene ble ikke feature-ekstrahert manuelt, men bevart direkte som tidsseriedata. Hvert opptak ble delt inn i vinduer av fast lengde ved hjelp av en glidende vinduing med 50 % overlapping (stride = window_size / 2), slik at hvert vindu ble ett individuelt treningspunkt. Det lave og det høye frekvensbåndet ble representert som to separate inndatakanaler, organisert som ein tensor med form (2, sekvenslengde). Normalisering ble utført per kanal basert på gjennomsnitt og standardavvik beregnet eksklusivt fra treningssettet, for å forhindre datalekkasje fra testsettet. Klassebalansen ble håndtert gjennom frekvensbasert klassevekting under trening, fremfor stratifisert splitting alene.

== Funksjonsoppbygning
=== MLP
Feature-konstruksjonen benytter den samme glidende vinduingen som CNN-modellen. De 300 vinduene per opptak representerer RF-signalet som en temporalt oppløst sekvens av frekvensbåndsenergier. Fra disse vinduene beregnes tre statistiske sammendrag per frekvensbånd — gjennomsnitt, standardavvik og maksimum — noe som gir 192 egenskaper per opptak. Denne tilnærmingen erstatter den opprinnelige manuelle konstruksjonen basert på FFT-topper og signalagregater, og sikrer at MLP-modellen opererer på den samme rike representasjonen som CNN-modellen, uten å måtte definere relevante frekvenser på forhånd.

=== CNN
CNN-modellen opererer direkte på rå signalverdier uten manuell feature-konstruksjon. Gjennom vinduingen genereres betydelig flere treningspunkter enn antall originalfiler tilsier, ettersom hvert opptak bidrar med flere overlappende vinduer. Dette er avgjørende siden datasettet kun inneholder 227 originalopptak. Den todimensjonale inndatastrukturen, med H- og L-båndet som separate kanaler langs første akse og tidspunkter langs andre akse, lar modellen selv oppdage relevante mønstre i begge frekvensbåndene og på tvers av dem, uten at det er nødvendig å forhåndsdefinere hvilke frekvenser som er diskriminerende.

== Maskinlærings-algoritme og valg av modell
=== MLP
MLP (Multi-Layer Perceptron) ble valgt fordi den er i stand til å modellere komplekse, ikke-lineære sammenhenger mellom de statistiske egenskapene ekstrahert fra frekvensbåndsvinduene. Modellen ble foretrukket over enklere lineære modeller for å fange opp nyanserte forskjeller mellom dronemodusen, og gir en naturlig sammenligning med CNN-modellen ettersom begge opererer på den samme underliggende vinduerepresentasjonen av signalet — men der CNN behandler vindusekvensen direkte, samler MLP informasjonen via statistisk pooling.

=== CNN
CNN (Convolutional Neural Network) ble valgt fordi den er spesialisert på å detektere lokale mønstre i sekvensielle data, noe som er velegnet for RF-signaler der karakteristiske strukturer kan opptre på ulike tidspunkter i opptaket. Arkitekturen som ble benyttet er DroneCNNMultiTask, en endimensjonal faltningsmodell med flere konvolusjonsblokker etterfulgt av adaptiv gjennomsnittspooling og to separate klassifikasjonshoveder. Modellen er utformet som en multitask-modell som simultant predikerer både dronefamilie og dronemodus. Begrunnelsen for dette er at felles representasjonslæring på tvers av de to målvariablene kan gi en mer robust intern representasjon av signalet, ettersom dronefamilie og dronemodus er tett knyttet til hverandre i RF-signaturen. Dette gir modellen mulighet til å utnytte informasjon som er nyttig for begge oppgavene, og kan potensielt bedre generaliseringsevnen sammenlignet med en modell som kun predikerer modus alene.

== Hyperparameter-strategi
=== MLP
Det ble benyttet en systematisk GridSearchCV-strategi med 5-fold stratifisert kryssvalidering for å utforske kombinasjoner av arkitektur, regularisering og læringsrater. Søkerommet dekket fire arkitekturalternativer — (32,), (64,), (32, 16) og (64, 32) — kombinert med fire regulariseringsverdier (α ∈ {0,05; 0,1; 0,5; 1,0}) og to læringsrater (0,001 og 0,0005). Scoringsmetrikken ble satt til macro-F1 i stedet for nøyaktighet, da ubalanserte klasser gjør at nøyaktighet er et misvisende mål. Med kun 181 treningsfiler favoriserte søket konsekvent de minste og sterkest regulariserte modellene, noe som bekreftet at datasettets størrelse setter et tak for nyttig modellkapasitet.

=== CNN
Hyperparameterne ble justert manuelt med utgangspunkt i valideringskurver, fremfor en automatisert søkestrategi. De viktigste parameterne var antall og størrelse på konvolusjonskanaler (standard: 32, 64, 128), kjernestørrelse (7), droppout-rate (0,30), læringsrate (0,001) og vektforfall (1 × 10⁻⁴) som implisitt L2-regularisering. Vindusstørrelse og stride ble holdt faste for å sikre reproduserbarhet. Tapet fra de to klassifikasjonshovedene ble vektet likt (1,0 for henholdsvis familie- og modushodet), da det ikke var grunnlag for å prioritere det ene fremfor det andre uten ytterligere eksperimentering. Justeringsprosessen tok sikte på å redusere gapet mellom trenings- og valideringsytelse, der høy treningsnøyaktighet kombinert med lav validerings-F1 ble tolket som et signal om å redusere modellkapasiteten eller øke regulariseringen.

== Trenings-prosedyre
=== MLP
Treningen benyttet log-loss kostfunksjon med Adam-optimalisatoren og adaptiv læringsrate for stabil konvergens. L2-regularisering (α) ble satt av GridSearchCV, og tidlig stopp med en tålmodighetsparameter på 50 iterasjoner uten forbedring sørget for at modellen ble fryst ved sin beste generaliseringsevne. Klasseubalansen ble kompensert ved å beregne frekvensbaserte prøvevekter (compute_sample_weight) på treningssettet og sende disse gjennom Pipeline-objektet til MLPClassifier under trening. Modellen ble trent med et internt valideringssett på 15 % av treningsdataene for early stopping-overvåkingen.

=== CNN
Treningen benyttet kryssentropi-tap for begge klassifikasjonshoveder, kombinert med Adam-optimalisatoren og vektforfall som implisitt L2-regularisering for å motvirke overtilpasning. For å håndtere klasseubalansen ble det benyttet frekvensbaserte klassevekter, beregnet som invertert frekvens, slik at sjeldne moduser fikk forholdsmessig høyere innflytelse på gradienten. Treningen ble avbrutt ved tidlig stopp basert på kombinert macro-F1 på valideringssettet, med en tålmodighetsparameter på 10 epoker uten forbedring. Modellvektene fra den best observerte epoken ble restaurert ved treningsslutt, slik at den endelige modellen representerte det punktet med best generaliseringsevne og ikke nødvendigvis siste iterasjon.